# Generated by Django 5.0.7 on 2024-09-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='https://www.wikipedia.org/'),
            preserve_default=False,
        ),
    ]
